### ISSUE TITLE
Photos for Milestone 4

### ISSUE THREAD

**Issue by md10600** [GSCSCI5530/Vector#10]
https://scontent-atl3-1.xx.fbcdn.net/v/t1.15752-9/40355716_675501672822784_5243406700429443072_n.jpg?_nc_cat=0&oh=f861e01c882949fda7d528889ef6346e&oe=5C2DDD1D

https://scontent-atl3-1.xx.fbcdn.net/v/t1.15752-9/40319041_2229590297318653_5029920025222316032_n.jpg?_nc_cat=0&oh=4fb1613d6cab6a371b5112d683da5a31&oe=5C2EA731

https://scontent-atl3-1.xx.fbcdn.net/v/t1.15752-9/40355702_683163672055511_1321930426209533952_n.jpg?_nc_cat=0&oh=679ad66f3d09ea0135d4954ef98f79d4&oe=5C3063B7

**Comment by JoshuaKyleLambert** [comment]
Photos added to the repo and wiki proper.
